[package]
name = "struction_character"
description = "Character controller with variable up, keyboard input mapping."
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
struction_physics = { workspace = true }
struction_gravity = { workspace = true }
