//! The player's Blender-authored look: the blood knight's rigid armor pieces ride
//! on the rig's joints.
//!
//! `assets/models/blood_knight.blend` (generated by `blood_knight.py`, then free
//! to edit in Blender) compiles to a `.smesh` through headless Blender at startup
//! when it changed, and again whenever it is saved while the playground runs.
//! Pieces are named `<joint>.<piece>` and modeled around the joint's rest
//! position, so each mesh is parented to its joint as is. Without Blender or a
//! compiled model, the rig keeps its simple shapes.

use std::path::Path;

use bevy::asset::io::file::FileAssetReader;
use bevy::prelude::*;
use struction_anim::{plugin::RigJoints, rig::Rig};
use struction_assets::{
    CompileStatus, CompiledModel, SourceWatcher, SourceWatcherPlugin, StructionAssetsPlugin,
    compile_asset, format::BundleMaterial,
};

const SOURCE: &str = "models/blood_knight.blend";
const COMPILED: &str = "models/blood_knight.smesh";

/// A rig that has been given a look (knight or shapes).
#[derive(Component)]
pub struct Dressed;

/// Armor piece spawned for a knight, removed when the model reloads.
#[derive(Component)]
pub struct KnightPiece;

#[derive(Resource)]
pub enum PlayerLook {
    Knight(Handle<CompiledModel>),
    Shapes,
}

/// Run condition for the fallback look.
pub fn uses_shapes(look: Res<PlayerLook>) -> bool {
    matches!(*look, PlayerLook::Shapes)
}

pub struct KnightPlugin;

impl Plugin for KnightPlugin {
    fn build(&self, app: &mut App) {
        let root = FileAssetReader::get_base_path().join("assets");
        let (source, compiled) = (root.join(SOURCE), root.join(COMPILED));
        let ready = prepare(&source, &compiled);
        app.add_plugins((StructionAssetsPlugin, SourceWatcherPlugin));
        if ready {
            app.world_mut().resource_mut::<SourceWatcher>().watch(
                &source,
                &compiled,
                Some(COMPILED.into()),
            );
            let handle = app.world().resource::<AssetServer>().load(COMPILED);
            app.insert_resource(PlayerLook::Knight(handle));
        } else {
            app.insert_resource(PlayerLook::Shapes);
        }
    }
}

/// Compiles the knight when its source changed. Reports whether a compiled model
/// is available.
fn prepare(source: &Path, compiled: &Path) -> bool {
    match compile_asset(source, compiled) {
        Ok(CompileStatus::Compiled) => info!("compiled {}", compiled.display()),
        Ok(CompileStatus::UpToDate) => {}
        Err(error) if compiled.is_file() => {
            warn!("using the last compiled blood knight: {error}");
        }
        Err(error) => {
            warn!("no blood knight, drawing the player with shapes: {error}");
            return false;
        }
    }
    true
}

/// Dresses new rigs once the model is loaded, and re-dresses every knight after
/// a hot reload. A model that fails to load falls back to shapes.
#[allow(clippy::too_many_arguments)]
pub fn dress_knights(
    mut commands: Commands,
    mut look: ResMut<PlayerLook>,
    mut reloads: MessageReader<AssetEvent<CompiledModel>>,
    asset_server: Res<AssetServer>,
    models: Res<Assets<CompiledModel>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    rigs: Query<(Entity, &Rig, &RigJoints, Has<Dressed>)>,
    pieces: Query<Entity, With<KnightPiece>>,
) {
    let PlayerLook::Knight(handle) = &*look else {
        return;
    };
    if asset_server.load_state(handle).is_failed() {
        error!("the blood knight failed to load; drawing the player with shapes");
        *look = PlayerLook::Shapes;
        return;
    }
    let Some(model) = models.get(handle) else {
        return;
    };
    let reloaded = reloads
        .read()
        .any(|event| matches!(event, AssetEvent::Modified { id } if *id == handle.id()));
    if reloaded {
        for piece in &pieces {
            commands.entity(piece).despawn();
        }
    }

    let mut palette = Vec::new();
    for (rig_entity, rig, joints, dressed) in &rigs {
        if dressed && !reloaded {
            continue;
        }
        if palette.is_empty() {
            palette = model
                .materials
                .iter()
                .map(|material| (material.name.clone(), materials.add(standard(material))))
                .collect();
        }
        for &joint in &joints.0 {
            commands.entity(joint).insert(Visibility::default());
        }
        let defs = rig.skeleton.joints();
        for node in &model.nodes {
            let joint_name = node.name.split('.').next().unwrap_or(&node.name);
            let Some(joint) = defs.iter().position(|def| def.name == joint_name) else {
                warn!("knight piece {:?} names no rig joint", node.name);
                continue;
            };
            for &mesh in &node.meshes {
                let mesh = &model.meshes[mesh as usize];
                let material = mesh
                    .material
                    .as_ref()
                    .and_then(|name| palette.iter().find(|(n, _)| n == name))
                    .map(|(_, handle)| handle.clone())
                    .unwrap_or_default();
                commands.spawn((
                    KnightPiece,
                    Mesh3d(mesh.lods[0].clone()),
                    MeshMaterial3d(material),
                    Transform::default(),
                    ChildOf(joints.0[joint]),
                ));
            }
        }
        commands.entity(rig_entity).insert(Dressed);
    }
}

/// Emission carries over as is: Bevy's default emissive ignores camera exposure, so
/// strength 1 is full brightness on screen, much as in Blender.
fn standard(material: &BundleMaterial) -> StandardMaterial {
    let [r, g, b] = material.emissive;
    StandardMaterial {
        base_color: LinearRgba::from_f32_array(material.base_color).into(),
        metallic: material.metallic,
        perceptual_roughness: material.roughness,
        emissive: LinearRgba::rgb(r, g, b),
        ..default()
    }
}

#[cfg(test)]
mod tests {
    use struction_anim::humanoid;
    use struction_assets::{Blender, import_source};

    use super::*;

    /// Every piece rides on a humanoid joint and is modeled around that joint's rest position,
    /// so parenting it to the joint without an offset puts it in place.
    #[test]
    fn knight_pieces_sit_on_humanoid_joints() {
        let blender = Blender::default();
        if !blender.is_available() {
            eprintln!("skipping: Blender not found (install it or set STRUCTION_BLENDER)");
            return;
        }
        let source = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("assets")
            .join(SOURCE);
        let scene = import_source(&source, &blender, false).unwrap();
        let rig = humanoid::rig();
        let defs = rig.skeleton.joints();
        let mut rest = Vec::<Vec3>::new();
        for def in defs {
            let parent = def.parent.map_or(Vec3::ZERO, |parent| rest[parent]);
            rest.push(parent + def.rest.translation);
        }

        assert!(scene.nodes.len() > 40, "{} pieces", scene.nodes.len());
        for node in &scene.nodes {
            let joint = node.name.split('.').next().unwrap();
            let index = defs
                .iter()
                .position(|def| def.name == joint)
                .unwrap_or_else(|| panic!("{} names no joint", node.name));
            assert!(node.parent.is_none(), "{} is nested", node.name);
            let at = Vec3::from(node.translation);
            assert!(
                at.distance(rest[index]) < 1e-4,
                "{} sits at {at}, its joint rests at {}",
                node.name,
                rest[index]
            );
        }
        for piece in ["chest.mark_drop", "hand_r.blade", "head.helm"] {
            assert!(scene.nodes.iter().any(|node| node.name == piece), "{piece}");
        }
    }
}
